# Generated by Django 4.0 on 2023-05-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_user_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
