# Generated by Django 4.0 on 2023-05-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_category_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
